/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandingsIndexRouteImport } from './routes/standings/index'
import { Route as StandingsTeamNameRouteImport } from './routes/standings/$teamName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsIndexRoute = StandingsIndexRouteImport.update({
  id: '/standings/',
  path: '/standings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsTeamNameRoute = StandingsTeamNameRouteImport.update({
  id: '/standings/$teamName',
  path: '/standings/$teamName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standings/$teamName': typeof StandingsTeamNameRoute
  '/standings': typeof StandingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standings/$teamName': typeof StandingsTeamNameRoute
  '/standings': typeof StandingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standings/$teamName': typeof StandingsTeamNameRoute
  '/standings/': typeof StandingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/standings/$teamName' | '/standings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/standings/$teamName' | '/standings'
  id: '__root__' | '/' | '/login' | '/standings/$teamName' | '/standings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StandingsTeamNameRoute: typeof StandingsTeamNameRoute
  StandingsIndexRoute: typeof StandingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings/': {
      id: '/standings/'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings/$teamName': {
      id: '/standings/$teamName'
      path: '/standings/$teamName'
      fullPath: '/standings/$teamName'
      preLoaderRoute: typeof StandingsTeamNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StandingsTeamNameRoute: StandingsTeamNameRoute,
  StandingsIndexRoute: StandingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
